# Copyright Roger Meier <r.meier@siemens.com>
# SPDX-License-Identifier:	GPL-2.0+

# build U-Boot on Travis CI - https://travis-ci.org/

sudo: required
dist: trusty

language: c

addons:
  apt:
    packages:
    - bc
    - libsdl1.2-dev
    - python
    - curl
    - lzop

install:
 # install latest device tree compiler
 - git clone --depth=1 --single-branch --branch master git://git.kernel.org/pub/scm/utils/dtc/dtc.git /tmp/dtc
 - make -j4 -C /tmp/dtc
 # install MIPS toolchain
 - curl -fsSL https://www.kernel.org/pub/tools/crosstool/files/bin/x86_64/4.9.0/x86_64-gcc-4.9.0-nolibc_mips-linux.tar.xz | tar -xJ -C /tmp/

env:
  global:
    - PATH=/tmp/dtc:/tmp/gcc-4.9.0-nolibc/mips-linux/bin:$PATH
    - CROSS_COMPILE=mips-linux-
    - CONFIG_USE_PRIVATE_LIBGCC=y
    - BUILD_DIR=build
    - HOSTCC="cc"
    - HOSTCXX="c++"

script:
 - ./MAKEALL $MAKEALL_OPTS

matrix:
  include:
    - env:
        - MAKEALL_OPTS="-b malta"
    - env:
        - MAKEALL_OPTS="-s danube"
    - env:
        - MAKEALL_OPTS="-s arx100"
    - env:
        - MAKEALL_OPTS="-s vrx200"
    - env:
        - MAKEALL_OPTS="-s xrx330"